services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - market-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_SECRET: ${BINANCE_SECRET}
      BITGET_API_KEY: ${BITGET_API_KEY}
      BITGET_SECRET: ${BITGET_SECRET}
      BITGET_PASSPHRASE: ${BITGET_PASSPHRASE}
      GATE_API_KEY: ${GATE_API_KEY}
      GATE_SECRET: ${GATE_SECRET}
      KUCOIN_API_KEY: ${KUCOIN_API_KEY}
      KUCOIN_SECRET: ${KUCOIN_SECRET}
      KUCOIN_PASSPHRASE: ${KUCOIN_PASSPHRASE}
      TRACK_SYMBOL: ${TRACK_SYMBOL:-BTCUSDT}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - market-net
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,yesoreyeram-boomtable-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - market-net
    restart: unless-stopped

networks:
  market-net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: