apiVersion: 1

datasources:
  - name: PostgreSQL-TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: market_analytics
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: true
    editable: true