apiVersion: 1

datasources:
  - name: PostgreSQL-TimescaleDB
    uid: postgres-timescale
    type: postgres
    access: proxy
    url: postgres:5432
    database: market_analytics
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true
    editable: true
    isDefault: true